In [1]:
import pymysql

In [13]:
pconn = pymysql.connect(host='sql.freedb.tech', user='freedb_sslp23', password='5!EG8uk8Yr7pDm&', port=3306)

In [14]:
import pandas as pd

In [15]:
players_infos = pd.read_csv("../data/players_infos.csv")

In [16]:
def create_table(pconn, df, table_name):

    cursor = pconn.cursor()

    # Define the table name and columns in your database
    columns = ', '.join([f"`{col}`" for col in df.columns])  # Wrap each column name in backticks

    # Prepare the SQL statement template for insertion
    placeholders = ', '.join(['%s'] * len(df.columns))
    sql = f"INSERT INTO {table_name} ({columns}) VALUES ({placeholders})"
    print(sql)
    df = df.fillna(-1)
    # Iterate over the rows in the DataFrame and insert them into the database
    for row in df.itertuples(index=False, name=None):
        cursor.execute(sql, row)
    
    print('Created table: ', table_name)
    # Commit the transaction
    pconn.commit()

    # Close the cursor
    cursor.close()

In [17]:
create_table(pconn, players_infos, 'PLAYERS_INFOS')

INSERT INTO PLAYERS_INFOS (`Season`, `Team`, `#`, `Link`, `PLAYER_ID`, `Player Name`, `Position`, `Age`, `Appearences`, `Played Games`, `Goals`, `Assists`, `Yellow`, `Second Yellow`, `Red`, `Come From Bench`, `Substituted`, `PPG`, `Minute Played`, `TEAM_ID`, `League`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)

OperationalError: (1046, 'No database selected')

In [8]:
players_infos

,Season,Team,#,Link,PLAYER_ID,Player Name,Position,Age,Appearences,Played Games,...,Assists,Yellow,Second Yellow,Red,Come From Bench,Substituted,PPG,Minute Played,TEAM_ID,League
0,2017-18,Manchester City,31,https://www.transfermarkt.co.uk/ederson/leistu...,238223,Ederson,Goalkeeper,23.0,57.0,45.0,...,0.0,2.0,0.0,0.0,0.0,1.0,2.49,NaN,281,GB1
1,2017-18,Manchester City,54,https://www.transfermarkt.co.uk/angus-gunn/lei...,201574,Angus Gunn,Goalkeeper,21.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,281,GB1
2,2017-18,Manchester City,-,https://www.transfermarkt.co.uk/joe-hart/leist...,40204,Joe Hart,Goalkeeper,30.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,281,GB1
3,2017-18,Manchester City,1,https://www.transfermarkt.co.uk/claudio-bravo/...,40423,Claudio Bravo,Goalkeeper,34.0,57.0,13.0,...,1.0,0.0,0.0,0.0,1.0,0.0,2.54,NaN,281,GB1
4,2017-18,Manchester City,5,https://www.transfermarkt.co.uk/john-stones/le...,186590,John Stones,Centre-Back,23.0,37.0,29.0,...,0.0,0.0,0.0,0.0,3.0,5.0,2.55,NaN,281,GB1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88905,2024-25,Sönderjyske,-,https://www.transfermarkt.co.uk/mikkel-ladefog...,806994,Mikkel Ladefoged,Centre-Forward,21.0,2.0,2.0,...,0.0,0.0,0.0,0.0,2.0,0.0,"0,00",NaN,5817,DK1
88906,2024-25,Sönderjyske,9,https://www.transfermarkt.co.uk/ivan-djantou/l...,1074629,Ivan Djantou,Centre-Forward,22.0,17.0,17.0,...,1.0,0.0,0.0,0.0,12.0,4.0,1.00,NaN,5817,DK1
88907,2024-25,Sönderjyske,24,https://www.transfermarkt.co.uk/olti-hyseni/le...,1034532,Olti Hyseni,Left Winger,17.0,10.0,9.0,...,2.0,0.0,0.0,0.0,4.0,5.0,1.00,NaN,5817,DK1
88908,2024-25,Sönderjyske,29,https://www.transfermarkt.co.uk/mikkel-hyllega...,694974,Mikkel Hyllegaard,Centre-Forward,25.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,5817,DK1
88909,2024-25,Sönderjyske,-,https://www.transfermarkt.co.uk/sebastian-esco...,1046263,Sebastian Escobar,Centre-Forward,19.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0,NaN,5817,DK1